---
- name: Start Storm in worker nodes
  hosts: betas
  gather_facts: yes
  become: True
  become_method: sudo
  tasks:
    - include_tasks: "./tasks/storm/complex/storm-worker-start.yaml"
      tags:
        - "storm-start"
