all:
  hosts:
    node0.pagnih03-271235.maki-test-pg0.utah.cloudlab.us:
      ansible_user: pagnih03
      ansible_ssh_private_key_file: ~/.ssh/id_rsa
      id: 0
    node1.pagnih03-271235.maki-test-pg0.utah.cloudlab.us:
      ansible_user: pagnih03
      ansible_ssh_private_key_file: ~/.ssh/id_rsa
      id: 1
    node2.pagnih03-271235.maki-test-pg0.utah.cloudlab.us:
      ansible_user: pagnih03
      ansible_ssh_private_key_file: ~/.ssh/id_rsa
      id: 2
    node3.pagnih03-271235.maki-test-pg0.utah.cloudlab.us:
      ansible_user: pagnih03
      ansible_ssh_private_key_file: ~/.ssh/id_rsa
      id: 3
    node4.pagnih03-271235.maki-test-pg0.utah.cloudlab.us:
      ansible_user: pagnih03
      ansible_ssh_private_key_file: ~/.ssh/id_rsa
      id: 4
    node5.pagnih03-271235.maki-test-pg0.utah.cloudlab.us:
      ansible_user: pagnih03
      ansible_ssh_private_key_file: ~/.ssh/id_rsa
      id: 5
